import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import HamburgerMenu from './hamburgermenu'
import Footer from './footer'

const montserrat = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Blog - Andromeda',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={montserrat.className}>
        <header className='flex w-full bg-slate-50 h-14 flex-wrap justify-between content-center p-8'>
          <div>Logo</div>
          <div className='flex'>
            
            <div className="flex">
          
              <input
                type="text"
                className="border border-gray-200 rounded-md px-3 py-1 focus:outline-none focus:ring-1 focus:ring-blue-500 hidden md:block"
                placeholder="Search"
              />
              <button
                className="ml-2 px-2 bg-slate-400 text-white rounded-md hidden md:block rounded-full mr-8"
              >
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 512 512"><path d="M464,428,339.92,303.9a160.48,160.48,0,0,0,30.72-94.58C370.64,120.37,298.27,48,209.32,48S48,120.37,48,209.32s72.37,161.32,161.32,161.32a160.48,160.48,0,0,0,94.58-30.72L428,464ZM209.32,319.69A110.38,110.38,0,1,1,319.69,209.32,110.5,110.5,0,0,1,209.32,319.69Z" fill="white"></path></svg>

              </button>
        </div>
        <HamburgerMenu />
          </div>
        </header>
        {children}
        <Footer />
      </body>
    </html>
  )
}
